name = "gaussian-memory"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "gaussian-memory"
database_id = "d052f7b7-a867-4124-be60-f61915f05e75"

[[vectorize]]
binding = "VECTORIZE"
index_name = "gaussian-memory-index"

[[kv_namespaces]]
binding = "KV"
id = "cc121b67ca2046b980e6053b9d066a96"

[triggers]
crons = ["0 6 * * *"]
